// the passwords that turn up first in every credential stuffing list. not a
// substitute for rate limiting - it only removes the guesses worth trying first
const common = new Set([
  '123456',
  '123456789',
  '12345678',
  'password',
  'qwerty123',
  'qwerty1',
  '111111',
  '12345',
  'secret',
  '123123',
  '1234567890',
  '1234567',
  '000000',
  'qwerty',
  'abc123',
  'password1',
  'iloveyou',
  '11111111',
  'dragon',
  'monkey',
  '123321',
  'football',
  'baseball',
  'welcome',
  'admin123',
  'letmein',
  'princess',
  'sunshine',
  'shadow',
  'master',
  'superman',
  'trustno1',
  'passw0rd',
  'password123',
  'qwertyuiop',
  'zaq12wsx',
  'asdfghjkl',
  '1q2w3e4r',
  '1qaz2wsx',
  'michael',
  'jordan23',
  'starwars',
  'whatever',
  'computer',
  'internet',
  'samsung',
  'liverpool',
  'chelsea',
  'arsenal',
  'pakistan',
  'karachi',
  'lahore',
  'islamabad',
  'changeme',
  'default',
  'welcome1',
  'test1234',
  'abcd1234',
  'a1b2c3d4',
  'iloveyou1',
  'nothing',
  'freedom',
  'ninja123',
]);

/** True if the password is one of the guesses an attacker starts with. */
export function isCommonPassword(password: string): boolean {
  return common.has(password.trim().toLowerCase());
}
